cue2flac: discard some bizzare unused functions; *: make it more accurate

diff --git a/cue2flac b/cue2flac
--- a/cue2flac
+++ b/cue2flac
@@ -5,37 +5,22 @@ cue2flac by AITap, 2009
 Published under GPLv3 or later
 WELCOME
 
-USAGE="\nUsage: $0 <source file> [CUE file] [-s]\n -s: silent, all external programs output is suspended\n"
+USAGE="Usage: $0 <source file> [CUE file]"
 
 function die () {
     echo -e $1
     exit 1
 }
 
-function check () {
-    if [ ! $? == 0 ]
-    then
-    die "$1"
-    else
-    [ "$2" ] && echo $2
-    fi
-}
-
-function debug () {
-	[ "$DEBUG" ] || return
-	if [ "$1" = "wait" ]
-	then
-		shift
-		echo ---debug: $@
-		read
-	else
-		echo ---debug: $@
-	fi
-}
-
 [ "$DEBUG" ] && set -x
 [ $# -eq 0 ] && die "$USAGE"
 [ -z "$1" ] && die "Source file not defined!"
+
+for prog in ffmpeg ffprobe cuetag cuebreakpoints shnsplit flac enconv lltag
+do
+	echo -n ">> Checking for $prog: "
+	which $prog || die "$prog not found!"
+done
 
 if [ -n "$2" ]
 then
@@ -50,10 +35,12 @@ else
 			break
 		fi
 	done
-	[ -z "$cue" ] && echo ">> CUE file not defined, assuming it's embedded"
+	if [ -z "$cue" ] && ! ffprobe -show_format "$1" 2>/dev/null | grep -q 'TAG:Cuesheet'
+	then
+		die ">> CUE file is not defined and there is no embedded CUE!"
+	fi
 fi
 
-debug wait "got cue"
 
 # код для получения cue из файла:
 # ffprobe -show_format | awk 'sub(/^TAG:Cuesheet=/,""){flag++}; /^TAG:/ && flag {exit}; flag{print}'
@@ -61,40 +48,6 @@ debug wait "got cue"
 # sed -n 'H;${g;s/.*TAG:Cuesheet=//;s/\nTAG:.*//;p}'
 # спасибо komar с #linux@RusNet
 # исходный вариант: | perl -ne '$flag=1 if s/^TAG:Cuesheet=//; exit if /^TAG:/; print if $flag'
-
-
-for prog in ffmpeg ffprobe cuetag cuebreakpoints shnsplit flac enconv
-do
-echo -n ">> Checking for $prog: "
-which $prog
-check "$prog not found!"
-done
-
-debug "programs found"
-
-if [ "$3" == "-s" ]
-then
-out=/dev/null
-echo ">> Working in silent mode."
-else
-out=/dev/stdout
-fi
-
-
-
-tempfile=$(date +%s.flac)
-
-case "${1}" in
-*.flac)
-	echo ">> File is already encoded, symlinking to ${tempfile}"
-	ln -s "$1" "$tempfile"
-	;;
-*)
-	echo ">> Creating temporary full FLAC file: $tempfile"
-	ffmpeg -i "$1" -acodec flac $tempfile &> $out
-	check ">> FFMPEG failed!"
-	;;
-esac
 
 if [ "$cue" ]
 then
@@ -107,41 +60,35 @@ else
 	ffprobe -show_format "$1" | sed -n 'H;${g;s/.*TAG:Cuesheet=//;s/\nTAG:.*//;p}' | enconv > $tempcue
 fi
 
-debug wait "cue got/recoded"
+test -s "$tempcue" || die ">> Someting went wrong"
 
-test -s "$tempcue"
-check ">> Someting went wrong"
+
+tempfile=$(date +%s.flac)
+
+case "${1}" in
+*.flac)
+	echo ">> File is already encoded, symlinking to ${tempfile}"
+	ln -s "$1" "$tempfile"
+	;;
+*)
+	echo ">> Creating temporary full FLAC file: $tempfile"
+	ffmpeg -i "$1" -acodec flac $tempfile &> $out || die ">> FFMPEG failed!"
+	;;
+esac
 
 echo ">> Splitting full FLAC into tracks..."
-
-cuebreakpoints "$tempcue" | shnsplit -o flac $tempfile &> $out
-
-check ">> Splitting failed!"
+cuebreakpoints "$tempcue" | shnsplit -o flac $tempfile &> $out || die ">> Splitting failed!"
 
 echo ">> Removing temporary FLAC: $tempfile"
-
 rm $tempfile &> $out
 
-check ">> Removing failed!"
-
 echo ">> Setting tags for splitted tracks..."
-
-cuetag "$tempcue" split-track*.flac &> $out
-
-check ">> Tag setting failed!"
+cuetag "$tempcue" split-track*.flac &> $out || die ">> Tag setting failed!"
 
 echo ">> Removing temporary CUE: $tempcue"
-
 rm $tempcue &> $out
 
 echo ">> Renaming split-track*.flac using tags..."
-
-for file in split-track*.flac; do
-title=$(lltag -S $file | grep -i '^ *title' | sed 's/.*=//;s|/||g') || next
-number=$(lltag -S $file | grep -i '^ *number' | sed 's/.*=//;s|/||g') || next
-mv -v $file "$(printf "%02d. %s.flac" "$number" "$title")"
-done &> $out
-
-check ">> Renaming failed!"
+lltag --no-tagging --rename "%n. %t" --rename-slash - split-track*.flac || die ">> Renaming failed!"
 
 echo ">> Everything is done."
