fix fatal error messages

diff --git a/flac2ogg b/flac2ogg
--- a/flac2ogg
+++ b/flac2ogg
@@ -72,9 +72,9 @@ do
 		artist=$(lltag -S "$file" | egrep -i '^ *ARTIST=' | sed 's/.*=//')
 		
 		echo -e '\033[1m>>  Recoding...\033[0m'
-		oggenc $OGGENC -a "$artist" -t "$title" -l "$album" -o "${localfile}.ogg" "${file}" &> $out || die ">>  Recoding ${localfile}.wav failed!"
+		oggenc $OGGENC -a "$artist" -t "$title" -l "$album" -o "${localfile}.ogg" "${file}" &> $out || die ">>  Recoding ${file} failed!"
 	else
-		die ">> You shouldn't have seen this. Forget it."
+		die ">> ${file} is nether a directory, nor a readable file!"
 	fi
 done
 exit 0
