update img2djvu
- ditch the default: I didn't use it much, anyway (ScanTailor makes
  acceptable b&w images)
- allow options between filenames: makes it possible to encode some
  of the pages as B&W and others as low-color
- add -dpi option to make dpi consistent across different formats

diff --git a/img2djvu b/img2djvu
--- a/img2djvu
+++ b/img2djvu
@@ -4,8 +4,10 @@ set -ue # die on undefined variables and non-zero exit code
 
 usage() {
 	cat <<USAGE
-Usage: $0 [-options] <target.djvu> <image files>
+Usage: $0 [-options] -o <target.djvu> <image files> [-more options <more image files>]
 Available options (in the order of application) are:
+	-o <file>
+		Set output file [REQUIRED]
 	-r <degrees>
 		rotate images by 90, 180 or 270 degrees
 	-s @<hpages>x<vpages>+<hpixels>+<vpixels>
@@ -26,150 +28,140 @@ Available options (in the order of application) are:
 	-m <threshold>
 		make pages monochrome
 		this option implies cjb2 compression
+	-d <dpi>
+		set dpi for encoders, default 600
 	-h
 		this help message
-
-If no options are set, applied defaults are: -g -c 3x40% -q 4:
-	- grey-scale the image
-	- stretch the contrast, blacking out <= 3% pixels and
-	  whiting out <= 40% pixels
-	- quantize, leaving 4 colors
-	- compress using cpaldjvu
 USAGE
 	exit $1
 }
 
-declare rotate= split= unsharp= greyscale= cstretch= quantize= threshold= manual= encoder= target=
+# encoding parameters and output file - from command line
+declare rotate= split= unsharp= greyscale= cstretch= quantize= threshold= manual= encoder= target= dpi=600
 
-while getopts ":r:s:u:gc:q:m:h" OPT; do
-	case "$OPT" in
-		r)
-			rotate="$OPTARG"
-			;;
-		s)
-			split="$OPTARG"
-			;;
-		u)
-			unsharp="$OPTARG"
-			;;
-		g)
-			greyscale=1
-			;;
-		c)
-			cstretch="$OPTARG"
-			;;
-		q)
-			quantize="$OPTARG"
-			;;
-		m)
-			threshold="$OPTARG"
-			;;
-		h)
-			usage 0
-			;;
-		*)
-			echo "Invalid option: $OPT $OPTARG"
-			usage 1
-			;;
-	esac
-	manual=1
-done
-
-shift $((OPTIND-1))
-
-if [ $# -le 1 ]; then
-	echo "Missing target filename or source filename[s]"
-	usage 1
-fi
-
-target="$1"
-shift
-
-if [ -e "$target" ]; then
-	echo "'$target' already exists! Will not overwrite it, aborting."
-	exit 1
-fi
-
-if [ ! $manual ]; then
-	greyscale=1
-	cstretch=3x40%
-	quantize=4
-fi
-
-echo "The following transformations will be applied, in order:"
-[ "$rotate" ] && echo "Rotate by $rotate degrees"
-[ "$split" ] && echo "Split by $split geometry"
-[ "$unsharp" ] && echo "Apply unsharp mask with parameters $unsharp"
-[ $greyscale ] && echo "Convert to grayscale"
-[ "$cstretch" ] && echo "Stretch contrast by $cstretch"
-[ "$quantize" ] && echo "Quantize leaving $quantize colors"
-[ "$threshold" ] && echo "Convert to monochrome with threshold $threshold"
-
+# encoding mode and encoder command - from encoding parameters
 declare -a encoder
-declare format=ppm
-
-if [ "$threshold" ]; then
-	encoder=("cjb2" "-verbose")
-	# cjb2 works with monochrome images
-	format=pbm
-elif [ "$quantize" ]; then
-	encoder=("cpaldjvu" "-verbose" "-colors" "$quantize")
-else
-	encoder=("c44")
-fi
-
-echo "Encode using $encoder"
-echo "Save to file $target"
-
+declare format
+# imagemagick processing parameters - from encoding parameters
 declare -a process
+# files to build target.djvu from
+declare -a compressed=()
 
-if [ "$rotate" ]; then
-	process+=("-rotate" "$rotate")
-fi
+while [ $# -gt 0 ]; do
+	if getopts ":d:o:r:s:u:gc:q:m:h" OPT; then
+		case "$OPT" in
+			r)
+				rotate="$OPTARG"
+				[ $rotate ] && echo "Will rotate by $rotate degrees clockwise"
+				;;
+			s)
+				split="$OPTARG"
+				[ $csplit ] && echo "Will split by $split pieces"
+				;;
+			u)
+				unsharp="$OPTARG"
+				[ $unsharp ] && echo "Will apply unsharp mask ($unsharp)"
+				;;
+			g)
+				if [ $greyscale ]; then
+					greyscale=
+				else
+					greyscale=1
+					echo "Will convert to greyscale"
+				fi
+				;;
+			c)
+				cstretch="$OPTARG"
+				threshold=""
+				[ $cstretch ] && echo "Will stretch contrast ($cstretch)"
+				;;
+			q)
+				quantize="$OPTARG"
+				threshold=""
+				[ "$quantize" ] && echo "Will quantize to $quantize colors"
+				;;
+			m)
+				threshold="$OPTARG"
+				quantize=""
+				[ "$threshold" ] && echo "Will convert to monochrome with threshold $threshold"
+				;;
+			h)
+				usage 0
+				;;
+			o)
+				if [ "$target" ]; then
+					echo "Target already set to $target! What did you mean? Aborting"
+					exit 1
+				fi
+				target="$OPTARG"
+				echo "Will save to $target"
+				;;
+			d)
+				dpi="$OPTARG"
+				echo "Will set dpi to $dpi"
+				;;
+			*)
+				echo "Invalid option: $OPT $OPTARG"
+				usage 1
+				;;
+		esac
+		shift $(($OPTIND-1)) # get $@ ready for next iteration
+		OPTIND=1 # get getopts ready, too
+	
+		# now we need to update the encoding mode
+		if [ "$threshold" ]; then
+			encoder=("cjb2" "-verbose" "-dpi" "$dpi")
+			# cjb2 works with monochrome images
+			format=pbm
+		elif [ "$quantize" ]; then
+			encoder=("cpaldjvu" "-verbose" "-colors" "$quantize" "-dpi" "$dpi")
+			format=ppm
+		else
+			encoder=("c44" "-dpi" "$dpi")
+			format=ppm
+		fi
+		# and update the processing parameters
+		process=("-verbose")
+		[ "$rotate" ] && process+=("-rotate" "$rotate")
+		[ "$split" ] && process+=("-crop" "$split")
+		[ "$unsharp" ] && process+=("-unsharp" "$unsharp")
+		[ $greyscale ] && process+=("-colorspace" "Gray")
+		[ "$cstretch" ] && process+=("-contrast-stretch" "$cstretch")
+		[ "$quantize" ] && process+=("+dither" "-colors" "$quantize") # disable dithering to help cpaldjvu
+		[ "$threshold" ] && process+=("-threshold" "$threshold")
+		continue
+	fi
 
-if [ "$split" ]; then
-	process+=("-crop" "$split")
-fi
+	if ! [ "$target" ]; then
+		echo "About to start processing files, but no target given (yet?)!"
+		echo "Please set the target before the files to process (-o option)."
+		echo "Aborting."
+		exit 1
+	fi
 
-if [ "$unsharp" ]; then
-	process+=("-unsharp" "$unsharp")
-fi
+	if [ -e "$target" ]; then
+		echo "'$target' already exists! Will not overwrite it, aborting."
+		exit 1
+	fi
 
-if [ $greyscale ]; then
-	process+=("-colorspace" "Gray")
-fi
-
-if [ "$cstretch" ]; then
-	process+=("-contrast-stretch" "$cstretch")
-fi
-
-if [ "$quantize" ]; then
-	# disable dithering to help cpaldjvu
-	process+=("+dither" "-colors" "$quantize")
-fi
-
-if [ "$threshold" ]; then
-	process+=("-threshold" "$threshold")
-fi
-
-echo "Running for each image: convert -verbose <file> ${process[*]} <file>.%d.$format"
-
-declare -a compressed
-
-for image in "$@"; do
-	convert -verbose "$image" "${process[@]}" "$image.%d.$format"
-	for part in "$image".*.$format; do
+	convert -verbose "$1" "${process[@]}" "$1.%d.$format"
+	for part in "$1".*.$format; do
 		# $encoder = ${encoder[0]} = program name
 		"${encoder[@]}" "$part" "$part".$encoder
 		rm -v "$part"
 		compressed+=("$part".$encoder)
 	done
+
+	shift 1 # we processed the file, update $@ accordingly
 done
 
-echo "Combining temp files into target $target"
+if [ "${#compressed[@]}" -eq 0 ]; then
+	echo "Files to process are not specified! Nothing to do, aborting"
+	usage 1
+fi
 
+echo "Combining temp files into target $target"
 djvm -c "$target" "${compressed[@]}"
 
 echo "Removing temp files"
-
 rm -v "${compressed[@]}"
