fix img2djvu
die if the target file already exists

diff --git a/img2djvu b/img2djvu
--- a/img2djvu
+++ b/img2djvu
@@ -85,6 +85,11 @@ fi
 target="$1"
 shift
 
+if [ -e "$target" ]; then
+	echo "'$target' already exists! Will not overwrite it, aborting."
+	exit 1
+fi
+
 if [ ! $manual ]; then
 	greyscale=1
 	cstretch=3x40%
