Revert "retry: allow optional timeout for the command to retry"
This reverts commit 6255d88bda857102e2f55ae2e8c6e9d625250d0e.

As it turns out, timeout of zero is not what it actually means. TODO: figure it out.

diff --git a/retry b/retry
--- a/retry
+++ b/retry
@@ -1,5 +1,5 @@
 #!/bin/sh
-# usage: RETRY_TIMEOUT=30 RETRY_SLEEP=10 retry my_command_which_may_fail_and_sould_be_retried
-while ! timeout ${RETRY_TIMEOUT:-0} "$@"; do
+# usage: RETRY_SLEEP=10 retry my_command_which_may_fail_and_sould_be_retried
+while ! "$@"; do
 	sleep ${RETRY_SLEEP:-5}
 done
